FERNET = "bmJPSFdTTFh6R0tBOEN4TW13ek9JOEZMZDhPUlppMjZDMmhfTWozdk1yTT0="
MONGO_URI = "mongodb+srv://easystorage:wbS4VPXsLur59ETT@easystorage.q0y7eu5.mongodb.net/easystorage?retryWrites=true&w=majority&appName=easystorage"